spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:bubu1234@localhost/assembly?authSource=admin
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings



message:
  groups:
    name: ASSEMBLY
  assembly-result:
    producer:
      name: READ-ASSEMBLY-RESULT
    consumer:
      name: RESULT-ASSEMBLY-ALREADY-READ
