spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:bubu1234@localhost/assembly?authSource=admin


server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings
# Set root logger level to DEBUG and its only appender to A1.
log4j:
  rootLogger: DEBUG, A1

  # A1 is set to be a ConsoleAppender.
  appender:
    A1: org.apache.log4j.ConsoleAppender

  # A1 uses PatternLayout.
    layout: org.apache.log4j.PatternLayout
#      ConversionPattern%-4r [%t] %-5p %c %x - %m%n